# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A mad world of pointers
email: shelajev@gmail.com
description: >
  Personal notes on
logo: "assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shelajev.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Oleg Å elajev'
bio: >
  Developer, writer, speaker, student.
  Java, Haskell, JavaScript.
author_image: "assets/images/author.jpg"
twitter_username: shelajev
github_username:  shelajev

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
